// <auto-generated />
using System;
using ApiVeiculos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiVeiculos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221219230025_AbstractModel")]
    partial class AbstractModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("ApiVeiculos.Model.Carro", b =>
                {
                    b.Property<int>("VeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRevisao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fabricante")
                        .HasColumnType("TEXT");

                    b.Property<int>("LitrosCombustivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placa")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeLugares")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quilometros")
                        .HasColumnType("INTEGER");

                    b.HasKey("VeiculoId");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("ApiVeiculos.Model.Moto", b =>
                {
                    b.Property<int>("VeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRevisao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fabricante")
                        .HasColumnType("TEXT");

                    b.Property<int>("LitrosCombustivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialQuadro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quilometros")
                        .HasColumnType("INTEGER");

                    b.HasKey("VeiculoId");

                    b.ToTable("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
